---
- name: Install mongodb
  hosts: all
  become: true
  tasks:
  - name: Import apt key
    apt_key:
      id: EA312927
      keyserver: keyserver.ubuntu.com

  - name: Add repo
    apt_repository:
      repo: deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
      state: present

  - name: Install mongodb
    apt:
      name: mongodb-org
      state: present

  - name: Enable mongod service
    systemd:
      name: mongod
      enabled: yes
